Repository PlasmaPy/plasmapy.github.io, pull requests merged in 2020-06, with the labels that each got.

#50 Update instructions on how to contribute
  .gitignore
  CODE_OF_CONDUCT.rst
  CONTRIBUTING.md
  LICENSE.md
  README.md
  pull_from_github.py
Labels: Nikola, content

#60 Add Initial YouTube Content
  web/conf.py
  web/files/assets/css/custom.css
  web/pages/index.md
Labels: content, enhancement

#62 Add Thomson Scatering Spectral Density to Feature Card
  web/images/features/thomson_spectral_density.png
  web/pages/index.md
Labels: content
