Repository PlasmaPy/plasmapy.github.io, pull requests merged in 2020-03, with the labels that each got.

#35 Created a general Meetings page & a 2020 Bryn Mawr Meetings page
  web/conf.py
  web/files/assets/css/custom.css
  web/pages/meetings/1st_workshop_2020_at_bryn_mawr/index.md
  web/pages/meetings/index.md
  web/pages/search.html
  web/plugins/__init__.py
  web/plugins/localsearch/MIT-LICENSE.txt
  web/plugins/localsearch/README.md
  web/plugins/localsearch/conf.py.sample
  web/plugins/localsearch/conf.py.sample.alt
  web/plugins/localsearch/localsearch.plugin
  web/plugins/localsearch/localsearch/__init__.py
  web/plugins/localsearch/localsearch/files/assets/css/img/loader.gif
  web/plugins/localsearch/localsearch/files/assets/css/img/search.png
  web/plugins/localsearch/localsearch/files/assets/css/tipuesearch.css
  web/plugins/localsearch/localsearch/files/assets/js/tipuesearch.js
  web/plugins/localsearch/localsearch/files/assets/js/tipuesearch.min.js
  web/plugins/localsearch/localsearch/files/assets/js/tipuesearch_set.js
  web/plugins/localsearch/localsearch/templates/jinja/localsearch.tmpl
  web/plugins/localsearch/localsearch/templates/mako/localsearch.tmpl
  web/plugins/localsearch/search-EXAMPLE.html
Labels: enhancement

#38 Localsearch-based search bar
  web/conf.py
  web/pages/meetings/1st_workshop_2020_at_bryn_mawr/index.md
Labels: enhancement

#44 Update 1st PlasmaPy Workshop page with Cancellation Note
  web/files/assets/css/custom.css
  web/pages/meetings/1st_workshop_2020_at_bryn_mawr/index.md
Labels: content

#43 Add post on version 0.3.1 release
  web/posts/plasmapy-v01-release.rst
  web/posts/plasmapy-v031-release.rst
Labels: content

#48 Make corrections to 0.3.1 blog post
  web/posts/plasmapy-v031-release.rst
Labels: Fixing typos/grammar

#47 Fix broken/miss-directed documentation links
  web/pages/contribute.md
  web/pages/vision.md
  web/posts/plasmapy-v01-release.rst
  web/posts/plasmapy-v011-bugfix-release.rst
  web/posts/plasmapy-v020-release.rst
Labels: bug
